# generated by zon2nix (https://github.com/nix-community/zon2nix)
{
  linkFarm,
  fetchzip,
}:
linkFarm "zig-packages" [
  {
    name = "122050b7d335326149738d72f74c8d1b7bdb89c07b12c1fa9b87fe61b69ae7750a21";
    path = fetchzip {
      url = "https://github.com/Not-Nik/raylib-zig/archive/ae533ad60fa31e5fc4fe4c4551002305f85c397e.tar.gz";
      hash = "sha256-xUYDjDc+OQOLYBD5kx5UGqkYiSJu9zxqm4MGiTCO23k=";
    };
  }
  {
    name = "1220cea8b32fa00460d5110fdf787a370f5b57bbf5296d68d77f90274a6990c6272e";
    path = fetchzip {
      url = "https://github.com/raysan5/raylib/archive/02d98a3e44b13584c98a7aaee0ca6fc5fb55a975.tar.gz";
      hash = "sha256-R16PPChi09Y7UpB1BNwycuO0lG10vL6or/S7Z+5PmRQ=";
    };
  }
]
