# generated by zon2nix (https://github.com/nix-community/zon2nix)

{ linkFarm, fetchzip }:

linkFarm "zig-packages" [
  {
    name = "122050b7d335326149738d72f74c8d1b7bdb89c07b12c1fa9b87fe61b69ae7750a21";
    path = fetchzip {
      url = "https://github.com/Not-Nik/raylib-zig/archive/devel.tar.gz";
      hash = "sha256-8+ORo034JpM8mzxGLQaBfl2W1toaGfulN+omIuTJROU=";
    };
  }
  {
    name = "12205f45151f556dd41348acc8a93099f19d6a2e830978ace86733ce0bfe52978812";
    path = fetchzip {
      url = "https://github.com/raysan5/raylib/archive/d6b22b17aecd2346d4fd1fc8ebaea8212e40008f.tar.gz";
      hash = "sha256-cNnzcV3FPRtNHNu97E4t+xPc1lwpY0heyG/dRTDSEQY=";
    };
  }
]
